module.exports = {
  JUST_ONE_TIME: true,
  JUST_ONE_MARKET: false,
  FAKE_ACCOUNTS: true,
  FAKE_BUY: true,
  FAKE_SELL: true,
  // NUM_MINUITES: 60,
  INSPECT_INTERVAL: 1000, // 한종목 조사 하는 딜레이
  TRIGGERING_INTERVAL: 100,

  // EXCLUDE_INSPECT_LIST: ['KRW-SRN', 'KRW-ADT', 'KRW-VTHO'],
  // EXCLUDE_ORDER_LISTS: ['KRW-ORBS', 'KRW-BTC']
};